Improve consumer API
arquivei/php-kafka-consumer pull request #28
Opened 2020-12-07 22:57 UTC by fcoedno

* Add a ConsumerBuilder class to ease the process of instantiating the
 Consumer class.

 * Simplify the handling of messages: Remove the need to inherit the
 abstract Consumer class and allow the user to provide any callable to
 handle the kafka messages.

 * Add the concept of message decoding in order to enable the user to
 create reusable decoder (e.g. json or kafka decoder). The return of the
 decoder is the value passed to the message handler callable.

All these improvements were extracted from the [php-kafka project](https://github.com/arquivei/php-kafka/releases/tag/v0.1-alpha), an attempt to build a more generic and developer-friendly php kafka client. 

This PR seeks to incorporate some of the changes proposed by [php-kafka](https://github.com/arquivei/php-kafka) while keeping total compatibility with the current API. This allows us to actually test this new API and refine it until we achieve a final API for a future major release.

2020-12-09 17:59 UTC, joesantos418 requested changes
This interface should be added to the integration tests.

2020-12-09 17:59 UTC, joesantos418 commented on readme.md
>  require_once 'vendor/autoload.php';
Might be a good idea to keep the old API doc in another README for historical purposes.

2020-12-09 17:59 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +        $this->securityProtocol = 'SASL_PLAINTEXT';
Some of these configs like brokers, security protocol and group id will cause the using application to not behave as intended if not set correctly. If we offer a more strict contract instead of dummy default values we can help the user catch config errors earlier.

2020-12-09 17:59 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +        $this->topics = $topics;
$topics is supposed to be an array of strings. If we validate that somewhere, we can help users catch configuration errors before consuming any messages.

2020-12-09 17:59 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +    public function withHandler(callable $handler): self
Defining handler as a callable makes it harder for the user to ensure they are using the right interface than it would be if we used a consumer interface instead.

2020-12-09 17:59 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +    public function withBroker(string $broker): self
The config takes a list of brokers, it should be called $brokers.

2020-12-10 19:37 UTC, fcoedno commented on src/ConsumerBuilder.php
> +    public function withHandler(callable $handler): self
This is really intended. The signature for handling messages is pretty straightforward: any callable that receives the message as first argument (also, it seems pretty natural to me).

Besides, in conjunction with the notion of middlewares, the idea is to allow the user to add any sort pre-processing and message transformations before passing it to the actual handler.

So, if we put too much restrictions in the handler signature this will not be possible.

It seems to me like a good tradeoff: We allow the user to have more flexibility, create reusable middlewares and reusable message transformations. The expected signature for this callable can be documented both in code and in the README.

As an example, one could provide a reusable JsonDecoderMiddleware, so that the message handlers receive a json object without needing to care about this in every consumer:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

class JsonDecoderMiddleware
{
    public function __invoke(string $message, callable $next): void
    {
        $decoded = json_decode($message);
        
        if (json_last_error() !== JSON_ERROR_NONE) {
            // If not a valid json, ignore it
            return;
        }
        
        $next($decoded);
    }
}

class MessageHandler
{
    public function __invoke(stdClass $message): void
    {
        echo "Hello {$message->userName}";
    }
}

$consumer = \Kafka\Consumer\ConsumerBuilder::create(['demo-topic'])
    ->withBroker('localhost:9092')
    ->withGroupId('demo-group')
    ->withMiddleware(new JsonDecoderMiddleware())
    ->withHandler(new MessageHandler())
    ->build();

$consumer->consume();
```

2020-12-10 20:52 UTC, fcoedno commented on src/ConsumerBuilder.php
> +        $this->securityProtocol = 'SASL_PLAINTEXT';
What would you suggest for a more strict contract? Maybe do not assign dummy values and let it break while building the consumer? Or maybe adding some validation of required fields?

2020-12-10 20:53 UTC, fcoedno commented on src/ConsumerBuilder.php
> +        $this->topics = $topics;
What about a variadic argument? Something like this:

```php
private function __construct(string ...$topics) { 
    // ...
}
```

2020-12-10 20:54 UTC, fcoedno commented on readme.md
>  require_once 'vendor/autoload.php';
Or maybe just keeping both in the current README and just remove it in a future major release, what do you think?

2020-12-10 21:47 UTC, joesantos418 commented on readme.md
>  require_once 'vendor/autoload.php';
I'm fine with that too.

2020-12-10 21:48 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +        $this->securityProtocol = 'SASL_PLAINTEXT';
I think adding the required values to the create() signature is a good way to ensure the builder will have all it needs to work.

2020-12-10 21:51 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +        $this->topics = $topics;
Variadics can get tricky. I think a simple array_map validation would be enough.

2020-12-10 21:52 UTC, joesantos418 commented on src/ConsumerBuilder.php
> +    public function withHandler(callable $handler): self
Like I mentioned in the other review, while I think interfaces do a better job at communicating contracts, I'm fine with this.

2020-12-11 12:11 UTC, fcoedno commented on src/ConsumerBuilder.php
> +        $this->securityProtocol = 'SASL_PLAINTEXT';
The only problem I see is loosing readability by adding too many parameters to the `create` method. But yeah, the brokers needs to be required and a dynamic group id in production might be problematic when scaling. However, for the securityProtocol, I think we can consider "PLAINTEXT" as the default one, at least this is the default for kafka as in the [docs](https://kafka.apache.org/0100/documentation.html#newconsumerconfigs).

So I suggest changing the create signature to: 

```php
public static function create(string $brokers, string $groupId, array $topics): self
{
    return new ConsumerBuilder($topics);
}
```

2020-12-11 19:37 UTC, fcoedno commented
@joesantos418 I've fixed the issues pointed out in the review and added further documentation.

2020-12-11 19:49 UTC, joesantos418 approved these changes

2020-12-17 13:44 UTC, merged