Add retry
arquivei/php-kafka-consumer pull request #31
Opened 2020-12-29 17:56 UTC by luiz-lucca-arquivei

A class has been added with all the retry logic that should be used in commit and message consumption.

Consumption starts to deal with timeout errors, retaining in the case of consumption timeout.

2020-12-29 17:57 UTC, fcoedno commented on src/Commit/RetryableCommitter.php
> +    private function doCommit(callable $commitFunc)
Onde the retry logic has been removed from this class, don't you it would be better to remove this `doCommit` method entirely?

2020-12-29 18:02 UTC, luiz-lucca-arquivei commented on src/Commit/RetryableCommitter.php
> +    private function doCommit(callable $commitFunc)
so good!

2020-12-29 18:06 UTC, fcoedno approved these changes

2020-12-29 19:09 UTC, joesantos418 requested changes
There are some PSR-12 violations, a quick check with an automated tool should help catch those.

2020-12-29 19:09 UTC, joesantos418 commented on src/Retry/Retryable.php
> +    public function retry(callable $function, int $currentRetries = 0, int $timeToWait = 1)
Might be a good idea to explicit the time unit in the variable name like `$delayInSeconds`.

2020-12-29 19:09 UTC, joesantos418 commented on src/Retry/Retryable.php
> +                $this->retry($function, ++$currentRetries, $timeToWait * 2);
This delay scales up exponentially. This is not explicit in the contract and it even may not be what the user wants. How about a way to configure how it changes as it keeps retrying?

2020-12-29 19:31 UTC, luiz-lucca-arquivei commented on src/Retry/Retryable.php
> +    public function retry(callable $function, int $currentRetries = 0, int $timeToWait = 1)
good good!

2020-12-29 19:32 UTC, luiz-lucca-arquivei commented on src/Retry/Retryable.php
> +                $this->retry($function, ++$currentRetries, $timeToWait * 2);
I added a new variable that says whether to consider exponential time. By default it comes as true ;)

2020-12-29 19:48 UTC, joesantos418 approved these changes

2021-01-04 12:11 UTC, joesantos418 approved these changes

2021-01-04 12:12 UTC, merged